### ISSUE TITLE
Error in new March beta

### ISSUE THREAD

**Issue by bschatzow** [ljmerza/ha-our-groceries#25]
## Version of the custom_component
1.3.11

## Configuration

```yaml
ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password
Add your logs here.

```

## Describe the bug
After installing the beta .3 our groceries stops running.

## Debug log

```text

Add your logs here.
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 7:17:29 PM (9 occurrences)
Last logged: 7:22:49 PM

Unable to install package ourgroceries==1.3.9: ERROR: Cannot install ourgroceries==1.3.9 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
More log info
Logger: homeassistant.config
Source: config.py:633
First occurred: 7:45:11 PM (23 occurrences)
Last logged: 7:49:07 PM

Package ourgrocery setup failed. Integration ourgroceries Requirements for ourgroceries not found: ['ourgroceries==1.3.9']. (See /config/integrations/ourgrocery.yaml:7).
Package ourgrocery setup failed. Integration ourgroceries Integration 'ourgroceries' not found. (See /config/integrations/ourgrocery.yaml:7).
