### ISSUE TITLE
Get a notification when number of items change

### ISSUE THREAD

**Issue by Kippy74** [ljmerza/ha-our-groceries#37]
Hi. 

Love this, but is it possible to get a notification on my phone  when my wife, or anybody else in our household, puts a new item to the shopping list?

With an automation that sends a notification to my phone when numbers of items change - but one when adding and not takes away an item on the list?

Anyone has an idea?

Best regards Kip

**Comment by bnhgit** [comment]
i know this is a bit old, but since i'm here for other reasons, and i because thought it was a good idea, i would comment on this in case others can benefit. 
What i did was added a template sensor:

`  - sensor:
      - name: Our Groceries Count
        state: "{{ state_attr('sensor.our_groceries','shopping_lists')|selectattr('name','==','Shopping List')|map(attribute='activeCount')|list|last }}"
`
replace the 'Shopping List' name with the name of the list you want to monitor.  That will store the number of items currently on the 'Shopping List' in sensor.our_groceries_count.

Then create an automation, and have it trigger only if the new state value is greater than the template sensor state. 

```
alias: Notify if Shopping list had an item added
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.our_groceries_count
condition:
  - condition: template
    value_template: "{{ trigger.from_state.state|int < trigger.to_state.state|int }}"
action:
  - service: notify.notify
    data:
      message: Shopping List count increased!
mode: single
```
There's probably a more elegant and/or efficient way to do this, but it works for me. Probably could avoid needing to create a template sensor at all, and just use a template trigger to compare the previous state to the current one.
